config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pets#index'
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
    validates :name, presence: true
    validates :spacies,presence: true, inclusion: {in: %w[dog cat ferret parrot snake]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

    def index
        @pets = Pet.all
    end

    def show
        @pet = Pet.find(params[:id])
    end
    
    def new
        @pet = Pet.new
    end
    
    def create
        @pet = Pet.new(pet_params)
        @pet.save
        redirect_to pet_path(@pet)
    end
    
    def edit
        @pet = Pet.find(params[:id])
    end
    
    def update 
        @pet = Pet.find(params[:id])
        @pet.update(pet_params)
        redirect_to pet_path(@pet)
    end
    
    def destroy
        @pet = Pet.find(params[:id])
        @pet.destroy
        redirect_to root_path
    end

    private

    def pet_params
        params.require(:pet).permit(:name, :address, :spacies, :found_on)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/edit.html.erb
<%= form_for(@pet) do |f|%>
<%=f.label :name  %>
<%=f.text_field :name  %>
<%=f.label :address  %>
<%=f.text_field :address  %>
<%=f.label :spacies,  type: 'select', collection: %w[dog cat ferret parrot snake]%>
<%=f.text_field :spacies  %>
<%=f.label :found_on  %>
<%=f.date_field :found_on  %>
<%= f.submit  %>
<% end %>

<%= link_to  "back home", pets_path %>

app/views/pets/index.html.erb
<ul>
<% @pets.each do |pet| %>
<li><%= link_to pet.name , pet_path(pet) %></li>
<% end %>
</ul>
<h3> <%= link_to  "create new pet profile", new_pet_path %></h3>

app/views/pets/new.html.erb
<%= form_for(@pet) do |f|%>
<%=f.labe :name  %>
<%=f.text_feild :name  %>
<%=f.labe :address  %>
<%=f.text_feild :address  %>
<%=f.labe :spacies  %>
<%=f.text_feild :spacies  %>
<%=f.labe :found_on  %>
<%=f.text_feild :found_on  %>
<%= f.submit  %>
<% end %>

app/views/pets/show.html.erb
<ul>
<li>name: <%= @pet.name %></li>
<li>species: <%= @pet.spacies %></li>
<li>address: <%= @pet.address %></li>
<li>found on: <%= @pet.found_on %></li>

</ul>
<%= link_to  "back home", pets_path %>
<%= link_to  "edit", edit_pet_path %>
<%= link_to  "delete", pet_path(@pet), method: 'delete', data:{confirm: 'Are you sure'} %>